program generate_krylov_reference
  ! Generates Krylov reference vectors for all CSR code paths.
  !
  ! Usage: cmake --build build --target generate_krylov_reference
  !        ./build/tests/support/generate_krylov_reference > tests/support/krylov_reference_data.f90
  !        (then rebuild: cmake --build build)

  use definitions, only: dp, iknd, simulation_config, region_spec, wavevector, &
    spatial_grid, paramStruct
  use sparse_matrices, only: csr_matrix, csr_free
  use parameters, only: paramDatabase
  use geometry, only: grid_init_rect, grid_free
  use confinement_init, only: confinementInitialization_2d
  use hamiltonian_wire, only: wire_workspace, wire_workspace_free, ZB8bandGeneralized
  use topological_analysis, only: bhz_wire_params, build_bhz_wire_hamiltonian
  use bdg_hamiltonian, only: build_bdg_hamiltonian_1d
  use krylov_helpers, only: krylov_chain
  implicit none

  integer, parameter :: K_CHAIN = 5
  complex(kind=dp), allocatable :: wire_vecs(:,:), peierls_vecs(:,:), &
    bhz_vecs(:,:), bdg_vecs(:,:), sc_loop_vecs(:,:), optics_wire_vecs(:,:), &
    gfactor_wire_vecs(:,:)

  ! Compute all reference vectors
  call compute_wire(wire_vecs)
  call compute_wire_peierls(peierls_vecs)
  call compute_bhz(bhz_vecs)
  call compute_bdg(bdg_vecs)
  call compute_sc_loop(sc_loop_vecs)
  call compute_optics_wire(optics_wire_vecs)
  call compute_gfactor_wire(gfactor_wire_vecs)

  ! Output declarations
  print '(a)', 'module krylov_reference_data'
  print '(a)', '  ! Reference vectors for Krylov snapshot tests.'
  print '(a)', '  !'
  print '(a)', '  ! AUTO-GENERATED by generate_krylov_reference - do not edit.'
  print '(a)', '  ! Regenerate: cmake --build build --target generate_krylov_reference'
  print '(a)', ''
  print '(a)', '  use definitions, only: dp'
  print '(a)', '  implicit none'
  print '(a)', ''
  print '(a)', '  private'

  call write_declaration('wire_ref', wire_vecs)
  call write_declaration('wire_peierls_ref', peierls_vecs)
  call write_declaration('bhz_ref', bhz_vecs)
  call write_declaration('bdg_ref', bdg_vecs)
  call write_declaration('sc_loop_ref', sc_loop_vecs)
  call write_declaration('optics_wire_ref', optics_wire_vecs)
  call write_declaration('gfactor_wire_ref', gfactor_wire_vecs)

  print '(a)', ''
  print '(a)', 'contains'
  print '(a)', ''

  call write_init_routine('wire_ref', wire_vecs)
  print '(a)', ''
  call write_init_routine('wire_peierls_ref', peierls_vecs)
  print '(a)', ''
  call write_init_routine('bhz_ref', bhz_vecs)
  print '(a)', ''
  call write_init_routine('bdg_ref', bdg_vecs)
  print '(a)', ''
  call write_init_routine('sc_loop_ref', sc_loop_vecs)
  print '(a)', ''
  call write_init_routine('optics_wire_ref', optics_wire_vecs)
  print '(a)', ''
  call write_init_routine('gfactor_wire_ref', gfactor_wire_vecs)

  print '(a)', 'end module krylov_reference_data'

  deallocate(wire_vecs, peierls_vecs, bhz_vecs, bdg_vecs, &
    sc_loop_vecs, optics_wire_vecs, gfactor_wire_vecs)

contains

  subroutine write_declaration(name, vecs)
    character(len=*), intent(in) :: name
    complex(kind=dp), intent(in) :: vecs(:,:)
    integer :: n, k
    character(len=512) :: line
    character(len=64) :: cname

    n = size(vecs, 1)
    k = size(vecs, 2)
    write(cname, '(a,a,i0,a,i0)') trim(name), '_n', n, '_k', k

    write(line, '(a,a)') '  public :: ', trim(cname)
    print '(a)', trim(line)
    write(line, '(a,a,a,i0,a,i0,a)') '  complex(kind=dp), save :: ', trim(cname), '(', n, ',', k, ')'
    print '(a)', trim(line)
    write(line, '(a,a)') '  public :: init_', trim(cname)
    print '(a)', trim(line)
  end subroutine write_declaration

  subroutine write_init_routine(name, vecs)
    character(len=*), intent(in) :: name
    complex(kind=dp), intent(in) :: vecs(:,:)
    integer :: n, k, j, i
    character(len=512) :: line
    character(len=64) :: cname

    n = size(vecs, 1)
    k = size(vecs, 2)
    write(cname, '(a,a,i0,a,i0)') trim(name), '_n', n, '_k', k

    write(line, '(a,a)') '  subroutine init_', trim(cname)
    print '(a)', trim(line)

    do j = 1, k
      write(line, '(a,a,a,i0,a)') '    ', trim(cname), '(:,', j, ') = [ &'
      print '(a)', trim(line)
      do i = 1, n
        if (i == n) then
          write(line, '(a,es23.16,a,es23.16,a)') '      cmplx(', real(vecs(i,j)), '_dp, ', aimag(vecs(i,j)), '_dp, dp) &'
        else
          write(line, '(a,es23.16,a,es23.16,a)') '      cmplx(', real(vecs(i,j)), '_dp, ', aimag(vecs(i,j)), '_dp, dp), &'
        end if
        print '(a)', trim(line)
      end do
      print '(a)', '    ]'
    end do

    write(line, '(a,a)') '  end subroutine init_', trim(cname)
    print '(a)', trim(line)
  end subroutine write_init_routine

  subroutine compute_wire(vecs)
    complex(kind=dp), allocatable, intent(out) :: vecs(:,:)
    integer, parameter :: nx = 3, ny = 3
    real(kind=dp), parameter :: dx = 5.0_dp, dy = 5.0_dp
    integer :: ngrid, ntot, ij
    type(spatial_grid) :: grid
    type(paramStruct), allocatable :: params(:)
    type(region_spec), allocatable :: regions(:)
    character(len=255), allocatable :: material_names(:)
    real(kind=dp), allocatable :: profile_2d(:,:)
    type(csr_matrix), allocatable :: kpterms_2d(:)
    type(csr_matrix) :: H_csr
    type(simulation_config) :: cfg
    integer :: mat2d(nx, ny)
    complex(kind=dp), allocatable :: seed(:)

    ngrid = nx * ny
    ntot = 8 * ngrid
    mat2d = 1

    call grid_init_rect(grid, nx, ny, dx, dy, mat2d)
    allocate(material_names(1))
    material_names(1) = "GaAs"
    allocate(params(1))
    call paramDatabase(material_names, 1, params)
    allocate(regions(1))
    regions(1)%material = "GaAs"

    call confinementInitialization_2d(grid, params, regions, profile_2d, kpterms_2d, FDorder=2)

    cfg%grid = grid
    cfg%confinement = 'wire'

    call ZB8bandGeneralized(H_csr, 0.05_dp, profile_2d, kpterms_2d, cfg)

    allocate(seed(ntot))
    seed = cmplx(1.0_dp, 0.0_dp, dp)
    call krylov_chain(H_csr, seed, K_CHAIN, vecs)

    deallocate(seed)
    call csr_free(H_csr)
    do ij = 1, size(kpterms_2d)
      call csr_free(kpterms_2d(ij))
    end do
    deallocate(kpterms_2d, profile_2d, params, regions, material_names)
    call grid_free(grid)
  end subroutine compute_wire

  subroutine compute_wire_peierls(vecs)
    complex(kind=dp), allocatable, intent(out) :: vecs(:,:)
    integer, parameter :: nx = 3, ny = 3
    real(kind=dp), parameter :: dx = 5.0_dp, dy = 5.0_dp
    integer :: ngrid, ntot, ij
    type(spatial_grid) :: grid
    type(paramStruct), allocatable :: params(:)
    type(region_spec), allocatable :: regions(:)
    character(len=255), allocatable :: material_names(:)
    real(kind=dp), allocatable :: profile_2d(:,:)
    type(csr_matrix), allocatable :: kpterms_2d(:)
    type(csr_matrix) :: H_bdg
    type(simulation_config) :: cfg
    type(wire_workspace) :: ws
    integer :: mat2d(nx, ny)
    complex(kind=dp), allocatable :: seed(:)

    ngrid = nx * ny
    mat2d = 1

    call grid_init_rect(grid, nx, ny, dx, dy, mat2d)
    allocate(material_names(1))
    material_names(1) = "GaAs"
    allocate(params(1))
    call paramDatabase(material_names, 1, params)
    allocate(regions(1))
    regions(1)%material = "GaAs"

    call confinementInitialization_2d(grid, params, regions, profile_2d, kpterms_2d, FDorder=2)

    cfg%grid = grid
    cfg%confinement = 'wire'
    cfg%bdg%enabled = .false.

    call build_bdg_hamiltonian_1d(H_bdg, cfg, profile_2d, kpterms_2d, &
      kz=0.0_dp, mu=0.0_dp, delta_0=0.001_dp, ws=ws, &
      B_vec=[1.0_dp, 0.0_dp, 0.0_dp], g_factor=0.0_dp)
    ntot = H_bdg%nrows

    allocate(seed(ntot))
    seed = cmplx(1.0_dp, 0.0_dp, dp)
    call krylov_chain(H_bdg, seed, K_CHAIN, vecs)

    deallocate(seed)
    call csr_free(H_bdg)
    call wire_workspace_free(ws)
    do ij = 1, size(kpterms_2d)
      call csr_free(kpterms_2d(ij))
    end do
    deallocate(kpterms_2d, profile_2d, params, regions, material_names)
    call grid_free(grid)
  end subroutine compute_wire_peierls

  subroutine compute_bhz(vecs)
    complex(kind=dp), allocatable, intent(out) :: vecs(:,:)
    type(csr_matrix) :: H_csr
    type(bhz_wire_params) :: bhz_params
    complex(kind=dp), allocatable :: seed(:)
    integer :: ntot

    bhz_params%N = 10
    bhz_params%dz = 5.8_dp
    bhz_params%A = 364.5_dp
    bhz_params%B = -686.0_dp
    bhz_params%D = -512.0_dp
    bhz_params%M = 10.0_dp

    call build_bhz_wire_hamiltonian(H_csr, bhz_params)
    ntot = H_csr%nrows

    allocate(seed(ntot))
    seed = cmplx(1.0_dp, 0.0_dp, dp)
    call krylov_chain(H_csr, seed, K_CHAIN, vecs)

    deallocate(seed)
    call csr_free(H_csr)
  end subroutine compute_bhz

  subroutine compute_bdg(vecs)
    complex(kind=dp), allocatable, intent(out) :: vecs(:,:)
    integer, parameter :: nx = 3, ny = 3
    real(kind=dp), parameter :: dx = 5.0_dp, dy = 5.0_dp
    integer :: ngrid, ntot, ij
    type(spatial_grid) :: grid
    type(paramStruct), allocatable :: params(:)
    type(region_spec), allocatable :: regions(:)
    character(len=255), allocatable :: material_names(:)
    real(kind=dp), allocatable :: profile_2d(:,:)
    type(csr_matrix), allocatable :: kpterms_2d(:)
    type(csr_matrix) :: H_bdg
    type(simulation_config) :: cfg
    type(wire_workspace) :: ws
    integer :: mat2d(nx, ny)
    complex(kind=dp), allocatable :: seed(:)

    ngrid = nx * ny
    mat2d = 1

    call grid_init_rect(grid, nx, ny, dx, dy, mat2d)
    allocate(material_names(1))
    material_names(1) = "GaAs"
    allocate(params(1))
    call paramDatabase(material_names, 1, params)
    allocate(regions(1))
    regions(1)%material = "GaAs"

    call confinementInitialization_2d(grid, params, regions, profile_2d, kpterms_2d, FDorder=2)

    cfg%grid = grid
    cfg%confinement = 'wire'
    cfg%bdg%enabled = .false.

    call build_bdg_hamiltonian_1d(H_bdg, cfg, profile_2d, kpterms_2d, &
      kz=0.0_dp, mu=0.5_dp, delta_0=0.001_dp, ws=ws)
    ntot = H_bdg%nrows

    allocate(seed(ntot))
    seed = cmplx(1.0_dp, 0.0_dp, dp)
    call krylov_chain(H_bdg, seed, K_CHAIN, vecs)

    deallocate(seed)
    call csr_free(H_bdg)
    call wire_workspace_free(ws)
    do ij = 1, size(kpterms_2d)
      call csr_free(kpterms_2d(ij))
    end do
    deallocate(kpterms_2d, profile_2d, params, regions, material_names)
    call grid_free(grid)
  end subroutine compute_bdg

  subroutine compute_sc_loop(vecs)
    ! SC loop path: wire Hamiltonian with SC enabled (snapshot BEFORE iteration).
    ! Same CSR assembly as wire, but cfg%SC = .true. to exercise SC path.
    complex(kind=dp), allocatable, intent(out) :: vecs(:,:)
    integer, parameter :: nx = 3, ny = 3
    real(kind=dp), parameter :: dx = 5.0_dp, dy = 5.0_dp
    integer :: ngrid, ntot, ij
    type(spatial_grid) :: grid
    type(paramStruct), allocatable :: params(:)
    type(region_spec), allocatable :: regions(:)
    character(len=255), allocatable :: material_names(:)
    real(kind=dp), allocatable :: profile_2d(:,:)
    type(csr_matrix), allocatable :: kpterms_2d(:)
    type(csr_matrix) :: H_csr
    type(simulation_config) :: cfg
    integer :: mat2d(nx, ny)
    complex(kind=dp), allocatable :: seed(:)

    ngrid = nx * ny
    ntot = 8 * ngrid
    mat2d = 1

    call grid_init_rect(grid, nx, ny, dx, dy, mat2d)
    allocate(material_names(1))
    material_names(1) = "GaAs"
    allocate(params(1))
    call paramDatabase(material_names, 1, params)
    allocate(regions(1))
    regions(1)%material = "GaAs"

    call confinementInitialization_2d(grid, params, regions, profile_2d, kpterms_2d, FDorder=2)

    cfg%grid = grid
    cfg%confinement = 'wire'
    cfg%sc%enabled = 1

    call ZB8bandGeneralized(H_csr, 0.05_dp, profile_2d, kpterms_2d, cfg)

    allocate(seed(ntot))
    seed = cmplx(1.0_dp, 0.0_dp, dp)
    call krylov_chain(H_csr, seed, K_CHAIN, vecs)

    deallocate(seed)
    call csr_free(H_csr)
    do ij = 1, size(kpterms_2d)
      call csr_free(kpterms_2d(ij))
    end do
    deallocate(kpterms_2d, profile_2d, params, regions, material_names)
    call grid_free(grid)
  end subroutine compute_sc_loop

  subroutine compute_optics_wire(vecs)
    ! Optics wire path: wire Hamiltonian used by optical spectra code.
    complex(kind=dp), allocatable, intent(out) :: vecs(:,:)
    integer, parameter :: nx = 3, ny = 3
    real(kind=dp), parameter :: dx = 5.0_dp, dy = 5.0_dp
    integer :: ngrid, ntot, ij
    type(spatial_grid) :: grid
    type(paramStruct), allocatable :: params(:)
    type(region_spec), allocatable :: regions(:)
    character(len=255), allocatable :: material_names(:)
    real(kind=dp), allocatable :: profile_2d(:,:)
    type(csr_matrix), allocatable :: kpterms_2d(:)
    type(csr_matrix) :: H_csr
    type(simulation_config) :: cfg
    integer :: mat2d(nx, ny)
    complex(kind=dp), allocatable :: seed(:)

    ngrid = nx * ny
    ntot = 8 * ngrid
    mat2d = 1

    call grid_init_rect(grid, nx, ny, dx, dy, mat2d)
    allocate(material_names(1))
    material_names(1) = "GaAs"
    allocate(params(1))
    call paramDatabase(material_names, 1, params)
    allocate(regions(1))
    regions(1)%material = "GaAs"

    call confinementInitialization_2d(grid, params, regions, profile_2d, kpterms_2d, FDorder=2)

    cfg%grid = grid
    cfg%confinement = 'wire'

    call ZB8bandGeneralized(H_csr, 0.05_dp, profile_2d, kpterms_2d, cfg)

    allocate(seed(ntot))
    seed = cmplx(1.0_dp, 0.0_dp, dp)
    call krylov_chain(H_csr, seed, K_CHAIN, vecs)

    deallocate(seed)
    call csr_free(H_csr)
    do ij = 1, size(kpterms_2d)
      call csr_free(kpterms_2d(ij))
    end do
    deallocate(kpterms_2d, profile_2d, params, regions, material_names)
    call grid_free(grid)
  end subroutine compute_optics_wire

  subroutine compute_gfactor_wire(vecs)
    ! Gfactor wire path: wire Hamiltonian used by g-factor code.
    complex(kind=dp), allocatable, intent(out) :: vecs(:,:)
    integer, parameter :: nx = 3, ny = 3
    real(kind=dp), parameter :: dx = 5.0_dp, dy = 5.0_dp
    integer :: ngrid, ntot, ij
    type(spatial_grid) :: grid
    type(paramStruct), allocatable :: params(:)
    type(region_spec), allocatable :: regions(:)
    character(len=255), allocatable :: material_names(:)
    real(kind=dp), allocatable :: profile_2d(:,:)
    type(csr_matrix), allocatable :: kpterms_2d(:)
    type(csr_matrix) :: H_csr
    type(simulation_config) :: cfg
    integer :: mat2d(nx, ny)
    complex(kind=dp), allocatable :: seed(:)

    ngrid = nx * ny
    ntot = 8 * ngrid
    mat2d = 1

    call grid_init_rect(grid, nx, ny, dx, dy, mat2d)
    allocate(material_names(1))
    material_names(1) = "GaAs"
    allocate(params(1))
    call paramDatabase(material_names, 1, params)
    allocate(regions(1))
    regions(1)%material = "GaAs"

    call confinementInitialization_2d(grid, params, regions, profile_2d, kpterms_2d, FDorder=2)

    cfg%grid = grid
    cfg%confinement = 'wire'

    call ZB8bandGeneralized(H_csr, 0.05_dp, profile_2d, kpterms_2d, cfg)

    allocate(seed(ntot))
    seed = cmplx(1.0_dp, 0.0_dp, dp)
    call krylov_chain(H_csr, seed, K_CHAIN, vecs)

    deallocate(seed)
    call csr_free(H_csr)
    do ij = 1, size(kpterms_2d)
      call csr_free(kpterms_2d(ij))
    end do
    deallocate(kpterms_2d, profile_2d, params, regions, material_names)
    call grid_free(grid)
  end subroutine compute_gfactor_wire

end program generate_krylov_reference
