module krylov_reference_data
  ! Reference vectors for Krylov snapshot tests.
  !
  ! Generated by: cmake --build build --target regenerate_krylov_references
  ! Regenerate when Hamiltonian construction intentionally changes.
  !
  ! Currently empty placeholder — reference data is populated by U6.

  use definitions, only: dp
  implicit none

  private

end module krylov_reference_data
