!===============================================================================
! perturbation_errors.f90
!
! Error Handling Framework for Numerical Perturbation Operations
!
! This module provides comprehensive error handling capabilities for numerical
! perturbation calculations, including error codes, messages, and recovery strategies.
!
! Author: Generated by speckit.implement
! Date: 2025-11-02
!===============================================================================

module perturbation_errors
  use definitions
  implicit none

  ! Error codes for numerical perturbation operations
  integer, parameter :: ERROR_NONE = 0
  integer, parameter :: ERROR_INVALID_CONFIG = 1
  integer, parameter :: ERROR_INVALID_TARGET_STATE = 2
  integer, parameter :: ERROR_INVALID_FIELD = 3
  integer, parameter :: ERROR_NUMERICAL_DIVERGENCE = 4
  integer, parameter :: ERROR_EIGENVALUE_FAILURE = 5
  integer, parameter :: ERROR_NON_CONVERGENCE = 6
  integer, parameter :: ERROR_MEMORY_ALLOCATION = 7
  integer, parameter :: ERROR_VALIDATION_FAILURE = 8
  integer, parameter :: ERROR_HAMILTONIAN_CONSTRUCTION = 9
  integer, parameter :: ERROR_STEP_SIZE_OUT_OF_RANGE = 10
  integer, parameter :: ERROR_DEGENERATE_STATES = 11
  integer, parameter :: ERROR_NON_HERMITIAN = 12
  integer, parameter :: ERROR_SPARSE_SOLVER = 13
  integer, parameter :: ERROR_WORKSPACE_INSUFFICIENT = 14

  ! Error severity levels
  integer, parameter :: SEVERITY_INFO = 0
  integer, parameter :: SEVERITY_WARNING = 1
  integer, parameter :: SEVERITY_ERROR = 2
  integer, parameter :: SEVERITY_FATAL = 3

  ! Maximum error message length
  integer, parameter :: MAX_ERROR_MSG_LENGTH = 256

  ! Error type for comprehensive error reporting
  type :: perturbation_error
    integer :: error_code = ERROR_NONE
    integer :: severity = SEVERITY_INFO
    character(len=MAX_ERROR_MSG_LENGTH) :: message = ''
    character(len=MAX_ERROR_MSG_LENGTH) :: context = ''
    logical :: can_recover = .true.
    character(len=MAX_ERROR_MSG_LENGTH) :: recovery_action = ''
  end type perturbation_error

  ! Error logger type
  type :: error_logger
    logical :: enabled = .true.
    character(len=256) :: log_file = ''
    integer :: num_errors = 0
    type(perturbation_error), allocatable :: error_history(:)
  end type error_logger

  ! Global error logger
  type(error_logger), save :: perturbation_log

  public :: perturbation_error, error_logger
  public :: ERROR_NONE, ERROR_INVALID_CONFIG, ERROR_INVALID_TARGET_STATE
  public :: ERROR_INVALID_FIELD, ERROR_NUMERICAL_DIVERGENCE, ERROR_EIGENVALUE_FAILURE
  public :: ERROR_NON_CONVERGENCE, ERROR_MEMORY_ALLOCATION, ERROR_VALIDATION_FAILURE
  public :: ERROR_HAMILTONIAN_CONSTRUCTION, ERROR_STEP_SIZE_OUT_OF_RANGE
  public :: ERROR_DEGENERATE_STATES, ERROR_NON_HERMITIAN, ERROR_SPARSE_SOLVER
  public :: ERROR_WORKSPACE_INSUFFICIENT
  public :: SEVERITY_INFO, SEVERITY_WARNING, SEVERITY_ERROR, SEVERITY_FATAL
  public :: initialize_error_logger
  public :: log_error
  public :: create_error
  public :: handle_error
  public :: get_error_message
  public :: clear_error_log
  public :: print_error_summary

contains

  !===========================================================================
  ! Initialize error logger
  !===========================================================================
  subroutine initialize_error_logger(log_filename)
    character(len=*), intent(in), optional :: log_filename

    perturbation_log%enabled = .true.
    perturbation_log%num_errors = 0

    if (present(log_filename)) then
      perturbation_log%log_file = log_filename
    else
      perturbation_log%log_file = 'perturbation_errors.log'
    end if

    if (allocated(perturbation_log%error_history)) then
      deallocate(perturbation_log%error_history)
    end if

  end subroutine initialize_error_logger

  !===========================================================================
  ! Log an error
  !===========================================================================
  subroutine log_error(error_info)
    type(perturbation_error), intent(in) :: error_info

    integer :: new_size
    type(perturbation_error), allocatable :: temp_history(:)

    if (.not. perturbation_log%enabled) return

    ! Expand error history array
    new_size = perturbation_log%num_errors + 1
    allocate(temp_history(new_size))

    if (perturbation_log%num_errors > 0) then
      temp_history(1:perturbation_log%num_errors) = perturbation_log%error_history
      deallocate(perturbation_log%error_history)
    end if

    temp_history(new_size) = error_info
    call move_alloc(temp_history, perturbation_log%error_history)
    perturbation_log%num_errors = new_size

    ! Print error to console
    call print_error_to_console(error_info)

  end subroutine log_error

  !===========================================================================
  ! Create an error object
  !===========================================================================
  function create_error(error_code, message, context, severity, can_recover, &
                        recovery_action) result(error_info)
    integer, intent(in) :: error_code
    character(len=*), intent(in) :: message
    character(len=*), intent(in), optional :: context
    integer, intent(in), optional :: severity
    logical, intent(in), optional :: can_recover
    character(len=*), intent(in), optional :: recovery_action
    type(perturbation_error) :: error_info

    error_info%error_code = error_code
    error_info%message = message
    error_info%severity = SEVERITY_ERROR
    error_info%can_recover = .true.

    if (present(context)) error_info%context = context
    if (present(severity)) error_info%severity = severity
    if (present(can_recover)) error_info%can_recover = can_recover
    if (present(recovery_action)) error_info%recovery_action = recovery_action

  end function create_error

  !===========================================================================
  ! Handle an error with automatic recovery if possible
  !===========================================================================
  subroutine handle_error(error_info, success)
    type(perturbation_error), intent(inout) :: error_info
    logical, intent(out) :: success

    success = .false.

    ! Log the error
    call log_error(error_info)

    ! Attempt recovery if possible
    if (error_info%can_recover) then
      select case (error_info%error_code)
        case (ERROR_STEP_SIZE_OUT_OF_RANGE)
          call recover_step_size_error(error_info, success)
        case (ERROR_NON_CONVERGENCE)
          call recover_convergence_error(error_info, success)
        case (ERROR_MEMORY_ALLOCATION)
          call recover_memory_error(error_info, success)
        case (ERROR_WORKSPACE_INSUFFICIENT)
          call recover_workspace_error(error_info, success)
        case default
          success = .false.
      end select
    end if

  end subroutine handle_error

  !===========================================================================
  ! Get human-readable error message
  !===========================================================================
  function get_error_message(error_code) result(message)
    integer, intent(in) :: error_code
    character(len=MAX_ERROR_MSG_LENGTH) :: message

    select case (error_code)
      case (ERROR_NONE)
        message = "Success: No error occurred"
      case (ERROR_INVALID_CONFIG)
        message = "Invalid configuration parameters"
      case (ERROR_INVALID_TARGET_STATE)
        message = "Invalid target state index"
      case (ERROR_INVALID_FIELD)
        message = "Invalid magnetic field parameters"
      case (ERROR_NUMERICAL_DIVERGENCE)
        message = "Numerical divergence detected"
      case (ERROR_EIGENVALUE_FAILURE)
        message = "Eigenvalue solver failure"
      case (ERROR_NON_CONVERGENCE)
        message = "Calculation failed to converge"
      case (ERROR_MEMORY_ALLOCATION)
        message = "Memory allocation failure"
      case (ERROR_VALIDATION_FAILURE)
        message = "Validation test failure"
      case (ERROR_HAMILTONIAN_CONSTRUCTION)
        message = "Hamiltonian construction error"
      case (ERROR_STEP_SIZE_OUT_OF_RANGE)
        message = "Perturbation step size out of valid range"
      case (ERROR_DEGENERATE_STATES)
        message = "Highly degenerate states detected"
      case (ERROR_NON_HERMITIAN)
        message = "Non-Hermitian Hamiltonian detected"
      case (ERROR_SPARSE_SOLVER)
        message = "Sparse eigenvalue solver error"
      case (ERROR_WORKSPACE_INSUFFICIENT)
        message = "Insufficient workspace memory"
      case default
        message = "Unknown error occurred"
    end select

  end function get_error_message

  !===========================================================================
  ! Clear error log
  !===========================================================================
  subroutine clear_error_log()
    if (allocated(perturbation_log%error_history)) then
      deallocate(perturbation_log%error_history)
    end if
    perturbation_log%num_errors = 0
  end subroutine clear_error_log

  !===========================================================================
  ! Print error summary
  !===========================================================================
  subroutine print_error_summary()
    integer :: i
    character(len=20) :: severity_str

    if (perturbation_log%num_errors == 0) then
      print *, "No errors logged."
      return
    end if

    print *, "=== Perturbation Error Summary ==="
    print *, "Total errors:", perturbation_log%num_errors

    do i = 1, perturbation_log%num_errors
      select case (perturbation_log%error_history(i)%severity)
        case (SEVERITY_INFO)
          severity_str = "INFO"
        case (SEVERITY_WARNING)
          severity_str = "WARNING"
        case (SEVERITY_ERROR)
          severity_str = "ERROR"
        case (SEVERITY_FATAL)
          severity_str = "FATAL"
        case default
          severity_str = "UNKNOWN"
      end select

      print *, i, ": [", trim(severity_str), "] ", &
               trim(perturbation_log%error_history(i)%message)
      if (len_trim(perturbation_log%error_history(i)%context) > 0) then
        print *, "    Context: ", trim(perturbation_log%error_history(i)%context)
      end if
    end do

  end subroutine print_error_summary

  !===========================================================================
  ! Print error to console
  !===========================================================================
  subroutine print_error_to_console(error_info)
    type(perturbation_error), intent(in) :: error_info
    character(len=20) :: severity_str

    select case (error_info%severity)
      case (SEVERITY_INFO)
        severity_str = "INFO"
      case (SEVERITY_WARNING)
        severity_str = "WARNING"
      case (SEVERITY_ERROR)
        severity_str = "ERROR"
      case (SEVERITY_FATAL)
        severity_str = "FATAL"
      case default
        severity_str = "UNKNOWN"
    end select

    print *, "[", trim(severity_str), "] ", trim(error_info%message)

    if (len_trim(error_info%context) > 0) then
      print *, "  Context: ", trim(error_info%context)
    end if

    
    if (len_trim(error_info%recovery_action) > 0) then
      print *, "  Recovery: ", trim(error_info%recovery_action)
    end if

  end subroutine print_error_to_console

  !===========================================================================
  ! Recovery routines for specific error types
  !===========================================================================

  subroutine recover_step_size_error(error_info, success)
    type(perturbation_error), intent(inout) :: error_info
    logical, intent(out) :: success

    ! Implementation will be added in User Story phases
    ! For now, just mark recovery as attempted
    error_info%recovery_action = "Adjusted step size to default value"
    success = .false.  ! Will be implemented later

  end subroutine recover_step_size_error

  subroutine recover_convergence_error(error_info, success)
    type(perturbation_error), intent(inout) :: error_info
    logical, intent(out) :: success

    ! Implementation will be added in User Story phases
    error_info%recovery_action = "Relaxed convergence tolerance"
    success = .false.  ! Will be implemented later

  end subroutine recover_convergence_error

  subroutine recover_memory_error(error_info, success)
    type(perturbation_error), intent(inout) :: error_info
    logical, intent(out) :: success

    ! Implementation will be added in User Story phases
    error_info%recovery_action = "Attempted workspace cleanup and reallocation"
    success = .false.  ! Will be implemented later

  end subroutine recover_memory_error

  subroutine recover_workspace_error(error_info, success)
    type(perturbation_error), intent(inout) :: error_info
    logical, intent(out) :: success

    ! Implementation will be added in User Story phases
    error_info%recovery_action = "Expanded workspace with growth factor"
    success = .false.  ! Will be implemented later

  end subroutine recover_workspace_error

end module perturbation_errors